name: dart_nats
description: A Dart client for the NATS messaging system. It's simple. Design to use with flutter easy to write no need to deal with complex asynchronous.
version: 0.1.0
homepage: https://github.com/chartchuo

environment:
  sdk: ">=2.1.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.9.4
